version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: csops_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-csops_admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-csops_pass}
      POSTGRES_DB: csops
    ports:
      - "5432:5432"
    volumes:
      - csops_pgdata:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
      - ./sql/reporting_views.sql:/docker-entrypoint-initdb.d/2_views.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-csops_admin} -d csops"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  csops_pgdata:

  
